conf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
	url(r'^$', 'core.views.home', name='home'),	
	url(r'^contact$', 'core.views.contact', name='contact'),
	url(r'^about$', 'core.views.about', name='about'),	
	url(r'^statistics$', 'core.views.display_chart', name='display_chart'),
	url(r'^import_data$', 'core.views.import_data', name='import_data'),
	url(r'^download_(?P<output_type>[^/]+)$', 'core.views.download', name='download'),	
	url(r'^check$', 'core.views.check', name='check'),	
	url(r'^view_(?P<view_type>[^/]+)', 'core.views.view', name='view'),	
	url(r'^galaxy_(?P<obj_id>[^/]+)', 'core.views.display_galaxy', name='display_galaxy'),	
	url(r'^pair_(?P<id>[^/]+)', 'core.views.display_pair', name='display_pair'),	
	url(r'^admin/', include(admin.site.urls)),
)

core/forms.py
# coding:utf-8
from django import forms

IMPORT_OPTIONS = (
('imponly', 'Import Only'),
('impchec', 'Import & Check for Pairs')
)
class ImportDataForm(forms.Form):
	file = forms.FileField()
	options = forms.MultipleChoiceField(required=True, widget=forms.RadioSelect, choices=IMPORT_OPTIONS)
	sql = forms.CharField(widget=forms.Textarea)
	mode = forms.BooleanField()

class ContactForm(forms.Form):
	contact_name = forms.CharField(label='Name', required=True)
	contact_email = forms.EmailField(label='Email', required=True)
	content = forms.CharField(
		label='Message',
		required=True,
		widget=forms.Textarea
	)

templates/about.html
{% extends "base.html" %}

{% block content %}
	
	<h1 class="page-header"> About the Tool </h1>
	
	<p class="text-justify">Colliding galaxies are astronomical events which can hide information about the evolution 
	of the universe. Although there are numerous methods and tools that can be used to detect these events, 
	they show themselves expensive when working with image processing and are often complex to implement and to use. 
	In order to facilitate the discovery of such events, this paper proposes the implementation of an algorithm 
	whose input data is a set of galaxies obtained from the Sloan Digital Sky Survey and returns a set of pairs of galaxies 
	that are likely to be in a process of collision. The tool was implemented using the Python programming language. 
	The results obtained from experiments show that the algorithm has good functionality, returning a favorable 
	percentage of galaxies that are in a process of interaction. Further work is proposed at the end of this paper, 
	in which we discuss the relevance of the results for posterior studies within the context of this research.</p>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>BIDHU</title>

    <!-- Bootstrap Core CSS -->
    <link href="../static/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="../static/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../static/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../static/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

	{% block extra-header %}{% endblock %}
	
</head>

<body{% block body-params %}{% endblock %}>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">						
            <div class="navbar-header">			
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Big Data of the Huge Universe</a>			
            </div>
            <!-- /.navbar-header -->

            <div class="navbar-default sidebar" role="navigation">				
                <div class="sidebar-nav navbar-collapse">	
                    <ul class="nav" id="side-menu">						
                        <li>
                            <a href="#"><i class="fa fa-bullseye fa-fw"></i>Galaxies<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="import_data"><i class="fa fa-upload fa-fw"></i>Import</a> 
                                </li>
								<li>
                                    <a href="{% url 'download' 'galaxies' %}"><i class="fa fa-download fa-fw"></i>Export</a>
                                </li>
                                <li>
                                    <a href="{% url 'view' 'galaxies' %}"><i class="fa fa-tasks fa-fw"></i>View</a>                                                                        
                                </li>								                                       
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
						<li>
                            <a href="#"><i class="fa fa-database fa-fw"></i>Pairs<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
								<li>
                                    <a href="{% url 'check' %}"><i class="fa fa-arrow-circle-right fa-fw"></i>Check</a>
                                </li>
								<li>
                                    <a href="{% url 'download' 'pairs' %}"><i class="fa fa-download fa-fw"></i>Export</a>
                                </li>
                                <li>
                                    <a href="{% url 'view' 'pairs' %}"><i class="fa fa-tasks fa-fw"></i>View</a>
                                </li>								                             
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
						<li>
                            <a href="statistics"><i class="fa fa-bar-chart-o fa-fw"></i>Statistics</a>
                        </li>                                
						<li>
                            <a href="contact"><i class="fa fa-question-circle fa-fw"></i>Contact</a>
                        </li> 
						<li>
                            <a href="about"><i class="fa fa-info-circle fa-fw"></i>About</a>
                        </li> 
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->								
            </div>
            <!-- /.navbar-static-side -->						
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">					
                    <div class="col-lg-12">
					{% block content %}
                        
					{% endblock %}
                    </div>					
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="../static/bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../static/bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../static/dist/js/sb-admin-2.js"></script>
	
	{% block extra-footer %} {% endblock %}
	
</body>

</html>

templates/check.html
{% extends "base.html" %}

{% block content %}

	{% if pairs == -1 %}
		<h1 class="page-header text-center">Empty Database</h1>
		<p>Database is empty.</p>
	{% elif pairs %}		
		<h1 class="page-header text-center">New Pairs Identified</h1>
		<p><a href="{% url 'view' 'pairs' %}">{{pairs}} pairs</a> were found by the tool.</p>	
	{% else %}
		<h1 class="page-header text-center">No Pair Identified</h1>
		<p>The tool could not identify new pairs.</p>
	{% endif %}
	
{% endblock %}

templates/contact.html
{% extends "base.html" %}

{% block content %}
	{% if  message == 'neutral'%}
	<h1 class="page-header"> Contact </h1>
	<div class="text-center">
		<form role="form" action="" method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Send Email</button>
		</form>
	</div>
	{% elif message == 'success' %}
	<h1 class="page-header"> Contact </h1>
	<div class="text-center">
		Your message was successfully sent. The team will answer you soon!
	</div>
	{% else %}
	<h1 class="page-header"> Contact </h1>
	<div class="text-center">
		Something went wrong while sending the message!
	</div>
	{% endif %}

{% endblock %}

templates/display.html
{% extends "base.html" %}

{% load core_tags %}

{% block extra-header %}

<style>	
	section {        
        position: absolute;
        top: 100%;
        left: 50%;
        margin-right: -50%;
        transform: translate(-50%, 0%) }
</style>

{% endblock %}

{% block content %}
	{% if galaxy %}
		<h1 class="page-header text-center"> Galaxy {{galaxy.obj_id}} </h1>
		<section class="col-lg-6">
			<table class="table">
					<tr>
						<th>ra:</th>
						<td>{{galaxy.ra}}</td>
					</tr>
					<tr>
						<th>dec:</th>
						<td>{{galaxy.dec}}</td>
					</tr>
			</table>
			
			<br />	
			
			<img src="http://skyservice.pha.jhu.edu/DR10/ImgCutout/getjpeg.aspx?ra={{galaxy.ra}}&dec={{galaxy.dec}}&scale=4&width=448&height=448&opt=&query=" height="448" width="448" />
		</section>
	{% else %}
		<h1 class="page-header text-center"> Pair {{pair.id}} </h1>
		<section class="col-lg-6">
			<table class="table">
					<tr>
						<th>Object 01:</th>
						<td><a href="{% url 'display_galaxy' pair.obj_one.obj_id %}">{{pair.obj_one}}</a></td>
					</tr>
					<tr>
						<th>Object 02:</th>
						<td><a href="{% url 'display_galaxy' pair.obj_two.obj_id %}">{{pair.obj_two}}</a></td>
					</tr>
			</table>
			
			<br />						
			
			<img src="http://skyservice.pha.jhu.edu/DR10/ImgCutout/getjpeg.aspx?{{pair|coordinates}}&scale=0.25&width=448&height=448&opt=&query=" height="448" width="448" />
		</section>
	{% endif %}

{% endblock %}

templates/export_csv.html
{% extends "base.html" %}

{% block content %}
	
	<h1 class="page-header text-center">Export Pairs to CSV File</h1>
	<p>Click <a href="{% url 'download' 'pairs' %}">here</a> to download a file with candidate pairs identified by the tool.</p>		
	
{% endblock %}

templates/import_data.html
{% extends "base.html" %}

{% block content %}

	{% if not galaxies %}		
		<h1 class="page-header text-center">Import Galaxies</h1>
		<div>
			<abbr title="Click here to change the import mode"><input type="button" name="source" id="source" value="CSV File" /></abbr>
			<form action="{% url 'import_data' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="form-group">
					<div id="mode" style="display:none">{{form.mode}}</div>
				</div>
				<div class="form-group">
					<div id="csv" style="display:block">{{form.file}}</div>
					<div id="sdss" style="display:none">{{form.sql}}</div>
				</div>
				<div class="form-group">
					<div class="radio">
						{% for radio in form.options %}
							{{radio}}
						{% endfor %}		
					</div>					
				</div>
				<input type="submit" value="Send Data" />
			</form>
		</div>
	{% elif form == "imponly" %}				
		<h1 class="page-header text-center">Galaxies Successfully Imported</h1>
		<p><a href="{% url 'view' 'galaxies' %}">{{galaxies}} galaxies</a> were added to the database.</p>
	{% elif form == "impchec" %}				
		<h1 class="page-header text-center">Galaxies Imported & Pairs Checked</h1>
		<p><a href="{% url 'view' 'galaxies' %}">{{galaxies}} galaxies</a> were added to the database. 
		From these galaxies, <a href="{% url 'view' 'pairs' %}">{{pairs}} pairs</a> were identified.</p>
	{% else %}
		<h1 class="page-header text-center">Error</h1>
		<p>Something went wrong, try again.</p>
	{% endif %}
	
{% endblock %}

{% block extra-footer %}
		
	<script>
		$("#source").click(function() {
			if($(this).val() == "CSV File"){
				$("#csv").toggle();
				$("#sdss").toggle();
				$("#id_mode").prop("checked", true);
				$(this).val("SDSS SQL Form");
			} else {
				$("#csv").toggle();
				$("#sdss").toggle();
				$("#id_mode").prop("checked", false);
				$(this).val("CSV File");
			}
			
		});
	</script>
	
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
	
	<h1 class="page-header">Welcome to BIDHU!</h1>
	
	<p>Please, use the menu to access the tool functionalities.</p>

{% endblock %}

templates/statistics.html
{% extends "base.html" %}

{% load core_tags %}

{% block extra-header %}

	<script type="text/javascript" src="../static/js/d3.min.js"></script>
	<script type="text/javascript" src="../static/bower_components/jquery/dist/jquery.js"></script>
	<script type="text/javascript" src="../static/js/plotly-basic.js"></script>	
	
{% endblock %}

{% block content %}
	
	<h1 class="page-header"> Statistics </h1>
	
	{% if all_objects %}
	
		<div id="numbers" style="block">
			<table class="table">
				<thead>
					<tr>
						<th>Total of Pairs</th>
						<th>Total of Galaxies</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>{{'pairs'|total}}</td>
						<td>{{'galaxies'|total}}</td>
					</tr>
				</tbody>
			</table>
		</div>
		
		<br />
		
		<div id="container" style="block"></div>
			<script>
				var galaxies = {
				  x: {{all_objects.galaxies.ra_list}},
				  y: {{all_objects.galaxies.dec_list}},
				  mode: 'markers',
				  type: 'scatter',
				  name: 'Galaxy',
				  text: {{all_objects.galaxies.obj_id_list|safe}},
				  marker: { size: 3 }
				};

				var pairs = {
				  x: {{all_objects.pairs.ra_list}},
				  y: {{all_objects.pairs.dec_list}},
				  mode: 'markers',
				  type: 'scatter',
				  name: 'Pair',
				  text: {{all_objects.pairs.obj_id_list|safe}},
				  marker: { size: 3 }
				};

				var data = [ galaxies, pairs ];

				var layout = {
				  xaxis: {
					range: [ {{coord_values.ra.min}}, {{coord_values.ra.max}} ]
				  },
				  yaxis: {
					range: [{{coord_values.dec.min}}, {{coord_values.dec.max}}]
				  },
				  title:'Galaxies & Pairs'
				};

				Plotly.newPlot('container', data, layout);
			</script>	
			
		{% else %}
		
			<p>Database is empty.</p>
			
		{% endif %}
		
{% endblock %}

{% block extra-footer %}
	
	<!--script src="../static/js/jquery-1.7.1.min.js"></script-->	
	
{% endblock %}

templates/table.html
{% extends "base.html" %}

{% load core_tags %}

{% block content %}

	{% if type == 1 %}		
		<h1 class="page-header text-center">Galaxy Table<a href="{% url 'download' 'galaxies' %}"><i class="fa fa-download fa-fw"></i></a></h1>		
		{% if lim < 100 %}
		<div style="float:left"><a href="{% url 'view' lim|url_string:'galaxies' %}"><i class="fa fa-arrow-left fa-fw"></i></a></div>
		{% elif lim > 100 %}
		<div style="float:left"><a href="{% url 'view' lim|url_string_before:'galaxies' %}"><i class="fa fa-arrow-left fa-fw"></i></a></div>
		<div style="float:right"><a href="{% url 'view' lim|url_string_after:'galaxies' %}"><i class="fa fa-arrow-right fa-fw"></i></a></div>
		{% else %}
		<div style="float:right"><a href="{% url 'view' lim|url_string_after:'galaxies' %}"><i class="fa fa-arrow-right fa-fw"></i></a></div>
		{% endif %}
		<div class="table-responsinve">
			<table class="table">
				<thead>
					<tr>
						<th>ID</th>
						<th>Right Ascension</th>
						<th>Declination</th>
					</tr>
				</thead>
				<tbody>
				{% for galaxy in objects %}
					<tr>
						<th><a href="{% url 'display_galaxy' galaxy.obj_id %}">{{galaxy.obj_id}}</a></th>
						<th>{{galaxy.ra}}</th>
						<th>{{galaxy.dec}}</th>
					</tr>					
				{% endfor %}
				</tbody>
			</table>
		</div>			
	{% elif type == 0 %}				
		<h1 class="page-header text-center">Pair Table<a href="{% url 'download' 'pairs' %}"><i class="fa fa-download fa-fw"></i></a></h1>		
		{% if lim < 100 %}
		<div style="float:left"><a href="{% url 'view' lim|url_string:'pairs' %}"><i class="fa fa-arrow-left fa-fw"></i></a></div>
		{% elif lim > 100 %}
		<div style="float:left"><a href="{% url 'view' lim|url_string_before:'pairs' %}"><i class="fa fa-arrow-left fa-fw"></i></a></div>
		<div style="float:right"><a href="{% url 'view' lim|url_string_after:'pairs' %}"><i class="fa fa-arrow-right fa-fw"></i></a></div>
		{% else %}
		<div style="float:right"><a href="{% url 'view' lim|url_string_after:'pairs' %}"><i class="fa fa-arrow-right fa-fw"></i></a></div>
		{% endif %}
		<div class="table-responsinve">
			<table class="table">
				<thead>
					<tr>
						<th>ID</th>
						<th>OBJ01</th>
						<th>OBJ02</th>
						<th>Angular Separation</th>
					</tr>
				</thead>
				<tbody>
				{% for pair in objects %}
					<tr>
						<th><a href="{% url 'display_pair' pair.id %}">{{pair.id}}</th>
						<th><a href="{% url 'display_galaxy' pair.obj_one.obj_id %}">{{pair.obj_one}}</a></th>
						<th><a href="{% url 'display_galaxy' pair.obj_two.obj_id %}">{{pair.obj_two}}</a></th>
						<th>{{pair.distance}}</th>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	{% else %}
		<h1 class="page-header text-center">Empty Database</h1>
		<p>Database is empty.</p>
	{% endif %}
	
{% endblock %}